#cloud-config

hostname: nxcore01

manage_etc_hosts: localhost

users:
  - name: core
    coreos-ssh-import-github: ncarlier

coreos:
  etcd:
    #generate a new token for each unique cluster from https://discovery.etcd.io/new
    #discovery: https://discovery.etcd.io/3b4f8671243ff94e47a3c6460d11aa38
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
      runtime: no
      content: |
        [Unit]
        Description=fleet
        [Service]
        ExecStart=/usr/bin/fleet
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API
        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both
        [Install]
        WantedBy=sockets.target
    - name: default.swap
      command: start
      content: |
        [Unit]
        Description=Activate SWAP
        [Swap]
        What=/dev/sda2
    - name: media-data.mount
      command: start
      content: |
        [Unit]
        Description=Mount data disk to /media/data
        [Mount]
        What=/dev/sda1
        Where=/media/data
        Type=btrfs
    - name: docker-link.service
      command: start
      content: |
        [Unit]
        Description=Symlink docker to data drive
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        Requires=media-data.mount
        Before=docker.service
        ExecStart=/usr/bin/ln -s /media/data/docker /var/lib/docker

